services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
      POSTGRES_DB: bank
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
