# fly.toml app configuration file generated for dogma-example on 2026-06-21T00:12:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dogma-example'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
