app            = 'dogma-example'
primary_region = 'syd'

[build]
    dockerfile = 'Dockerfile.fly'

[http_service]
    internal_port        = 8080
    force_https          = true
    auto_start_machines  = true
    auto_stop_machines   = 'off'
    min_machines_running = 1

[[vm]]
    memory   = '256mb'
    cpu_kind = 'shared'
    cpus     = 1
