// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account.proto

package proto // import "github.com/dogmatiq/example/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// OpenAccountRequest is the request initiated by the client to open an account.
type OpenAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAccountRequest) Reset()         { *m = OpenAccountRequest{} }
func (m *OpenAccountRequest) String() string { return proto.CompactTextString(m) }
func (*OpenAccountRequest) ProtoMessage()    {}
func (*OpenAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_b8f0838b6d874b33, []int{0}
}
func (m *OpenAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAccountRequest.Unmarshal(m, b)
}
func (m *OpenAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAccountRequest.Marshal(b, m, deterministic)
}
func (dst *OpenAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAccountRequest.Merge(dst, src)
}
func (m *OpenAccountRequest) XXX_Size() int {
	return xxx_messageInfo_OpenAccountRequest.Size(m)
}
func (m *OpenAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAccountRequest proto.InternalMessageInfo

func (m *OpenAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *OpenAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// OpenAccountRequest is the request initiated by the client to open an account.
type OpenAccountResponse struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAccountResponse) Reset()         { *m = OpenAccountResponse{} }
func (m *OpenAccountResponse) String() string { return proto.CompactTextString(m) }
func (*OpenAccountResponse) ProtoMessage()    {}
func (*OpenAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_b8f0838b6d874b33, []int{1}
}
func (m *OpenAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAccountResponse.Unmarshal(m, b)
}
func (m *OpenAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAccountResponse.Marshal(b, m, deterministic)
}
func (dst *OpenAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAccountResponse.Merge(dst, src)
}
func (m *OpenAccountResponse) XXX_Size() int {
	return xxx_messageInfo_OpenAccountResponse.Size(m)
}
func (m *OpenAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAccountResponse proto.InternalMessageInfo

func (m *OpenAccountResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *OpenAccountResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenAccountRequest)(nil), "proto.OpenAccountRequest")
	proto.RegisterType((*OpenAccountResponse)(nil), "proto.OpenAccountResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	// OpenAccount is a service handler to process OpenAccountRequest.
	OpenAccount(ctx context.Context, in *OpenAccountRequest, opts ...grpc.CallOption) (*OpenAccountResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) OpenAccount(ctx context.Context, in *OpenAccountRequest, opts ...grpc.CallOption) (*OpenAccountResponse, error) {
	out := new(OpenAccountResponse)
	err := c.cc.Invoke(ctx, "/proto.Account/OpenAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	// OpenAccount is a service handler to process OpenAccountRequest.
	OpenAccount(context.Context, *OpenAccountRequest) (*OpenAccountResponse, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_OpenAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).OpenAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Account/OpenAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).OpenAccount(ctx, req.(*OpenAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenAccount",
			Handler:    _Account_OpenAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/account.proto",
}

func init() { proto.RegisterFile("proto/account.proto", fileDescriptor_account_b8f0838b6d874b33) }

var fileDescriptor_account_b8f0838b6d874b33 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x03, 0xf3, 0x84, 0x58, 0xc1, 0x94,
	0x92, 0x3b, 0x97, 0x90, 0x7f, 0x41, 0x6a, 0x9e, 0x23, 0x44, 0x2e, 0x28, 0xb5, 0xb0, 0x34, 0xb5,
	0xb8, 0x44, 0x48, 0x96, 0x8b, 0x0b, 0xaa, 0x3a, 0x3e, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x33, 0x88, 0x13, 0x2a, 0xe2, 0x99, 0x22, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1,
	0x04, 0x96, 0x00, 0xb3, 0x95, 0x3c, 0xb8, 0x84, 0x51, 0x0c, 0x2a, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x25, 0xc3, 0x24, 0xa3, 0x40, 0x2e, 0x76, 0xa8, 0x29, 0x42, 0x6e, 0x5c, 0xdc, 0x48, 0x86, 0x0a,
	0x49, 0x42, 0xdc, 0xae, 0x87, 0xe9, 0x62, 0x29, 0x29, 0x6c, 0x52, 0x10, 0x37, 0x28, 0x31, 0x38,
	0x29, 0x47, 0x29, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0xe4,
	0xa7, 0xe7, 0x26, 0x96, 0x64, 0x16, 0xea, 0xa7, 0x56, 0x24, 0xe6, 0x16, 0xe4, 0xa4, 0xea, 0x83,
	0xb5, 0x26, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xcb, 0xe6, 0x60,
	0x2f, 0x01, 0x00, 0x00,
}
